#!/usr/bin/env python
from pax import core

config_overload = """
[pax]
input = 'XED.XedInput'
#input = 'fax.FaX'

dsp = ['SimpleDSP.BuildWaveforms',
       'SimpleDSP.ApplyFilters',
       'SimpleDSP.FindPeaks',
       'SimpleDSP.SplitPeaks',
       'SimpleDSP.IdentifyPeaks',
       ]
transform = []

output = [
            'Plotting.PlotWaveform',
            'CSV.WritePeaksCSV',
         ]

[XED.XedInput]
filename = "xe100_120402_2000_000000.xed"
#filename = "xe100_120306_1132_000000.xed"

[Plotting.PlotWaveform]
waveforms_to_plot = (
        {'internal_name': 'veto', 'plot_label': 'Veto (raw)'},
        {'internal_name': 'tpc',  'plot_label': 'TPC (raw)'},
        {'internal_name': 'tpc_s2',  'plot_label': 'TPC (filtered for s2)'},
        {'internal_name': 'tpc_s1',  'plot_label': 'TPC (filtered for s1)'},
    )

"""

if __name__ == '__main__':
    core.processor(config_overload)